// Semi-Markov Model Parameters with State Memory
// Auto-generated from interaction data

#ifndef SMM_PARAMETERS_H
#define SMM_PARAMETERS_H

// State definitions
#define STATE_AFTER_SCROLL 0
#define STATE_AFTER_LIKE 1
#define STATE_AFTER_DUBIOUS 2

// Action definitions
#define ACTION_SCROLL 0
#define ACTION_LIKE 1
#define ACTION_DUBIOUS_SCROLL 2


// Parameters for WATCHING_AFTER_SCROLL state
const float MEAN_DWELL_AFTER_SCROLL = 5.074521f;
const float DWELL_RATE_AFTER_SCROLL = 0.197063f;

const float PROB_SCROLL_AFTER_SCROLL = 0.797872f;
const float PROB_LIKE_AFTER_SCROLL = 0.138298f;
const float PROB_DUBIOUS_AFTER_SCROLL = 0.063830f;

const float CUM_PROB_SCROLL_AFTER_SCROLL = 0.797872f;
const float CUM_PROB_LIKE_AFTER_SCROLL = 0.936170f;
const float CUM_PROB_DUBIOUS_AFTER_SCROLL = 1.000000f;

// Parameters for WATCHING_AFTER_LIKE state
const float MEAN_DWELL_AFTER_LIKE = 5.560357f;
const float DWELL_RATE_AFTER_LIKE = 0.179845f;

const float PROB_SCROLL_AFTER_LIKE = 1.000000f;
const float PROB_LIKE_AFTER_LIKE = 0.000000f;
const float PROB_DUBIOUS_AFTER_LIKE = 0.000000f;

const float CUM_PROB_SCROLL_AFTER_LIKE = 1.000000f;
const float CUM_PROB_LIKE_AFTER_LIKE = 1.000000f;
const float CUM_PROB_DUBIOUS_AFTER_LIKE = 1.000000f;

// Parameters for WATCHING_AFTER_DUBIOUS state
const float MEAN_DWELL_AFTER_DUBIOUS = 9.252714f;
const float DWELL_RATE_AFTER_DUBIOUS = 0.108076f;

const float PROB_SCROLL_AFTER_DUBIOUS = 0.714286f;
const float PROB_LIKE_AFTER_DUBIOUS = 0.142857f;
const float PROB_DUBIOUS_AFTER_DUBIOUS = 0.142857f;

const float CUM_PROB_SCROLL_AFTER_DUBIOUS = 0.714286f;
const float CUM_PROB_LIKE_AFTER_DUBIOUS = 0.857143f;
const float CUM_PROB_DUBIOUS_AFTER_DUBIOUS = 1.000000f;

// Lookup arrays for efficient state-dependent parameter access
const float MEAN_DWELL_BY_STATE[3] = {
    MEAN_DWELL_AFTER_SCROLL,
    MEAN_DWELL_AFTER_LIKE, 
    MEAN_DWELL_AFTER_DUBIOUS
};

const float DWELL_RATE_BY_STATE[3] = {
    DWELL_RATE_AFTER_SCROLL,
    DWELL_RATE_AFTER_LIKE,
    DWELL_RATE_AFTER_DUBIOUS
};

const float CUM_PROB_SCROLL_BY_STATE[3] = {
    CUM_PROB_SCROLL_AFTER_SCROLL,
    CUM_PROB_SCROLL_AFTER_LIKE,
    CUM_PROB_SCROLL_AFTER_DUBIOUS
};

const float CUM_PROB_LIKE_BY_STATE[3] = {
    CUM_PROB_LIKE_AFTER_SCROLL,
    CUM_PROB_LIKE_AFTER_LIKE,
    CUM_PROB_LIKE_AFTER_DUBIOUS
};

const float CUM_PROB_DUBIOUS_BY_STATE[3] = {
    CUM_PROB_DUBIOUS_AFTER_SCROLL,
    CUM_PROB_DUBIOUS_AFTER_LIKE,
    CUM_PROB_DUBIOUS_AFTER_DUBIOUS
};

#endif // SMM_PARAMETERS_H
